-- 1. Crear el usuario sobre el que está definido el esquema
CREATE USER APP_USER IDENTIFIED BY "OCI_devops_2026";

-- Darle permisos básicos de conexión y desarrollo
GRANT CONNECT, RESOURCE TO APP_USER;
GRANT CREATE SESSION TO APP_USER;

-- En Autonomous Database, es vital asignar cuota en el tablespace DATA
ALTER USER APP_USER QUOTA UNLIMITED ON DATA;

-- (Opcional) Si vas a usar herramientas web como APEX o Database Actions
BEGIN
    ORDS.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'APP_USER',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'app_user',
        p_auto_rest_auth => FALSE
    );
    COMMIT;
END;
/

-- 2. Creación de tablas
CREATE TABLE APP_USER.Project (
    projectId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE APP_USER.TaskType (
    typeId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    CONSTRAINT chk_task_type CHECK (name IN ('Feature', 'Bug', 'Documentation', 'Research', 'Other'))
);

CREATE TABLE APP_USER.Team (
    teamId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    managerId NUMBER
);

CREATE TABLE APP_USER.Users (
    userId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegramId NUMBER UNIQUE NOT NULL,
    username VARCHAR2(100) UNIQUE,
    firstName VARCHAR2(100) NOT NULL,
    lastName VARCHAR2(100),
    role VARCHAR2(20) NOT NULL,
    teamId NUMBER,
    password VARCHAR2(255),
    CONSTRAINT chk_user_role CHECK (role IN ('DEVELOPER', 'MANAGER')),
    CONSTRAINT fk_user_team FOREIGN KEY (teamId) REFERENCES APP_USER.Team(teamId)
);

CREATE TABLE APP_USER.Project_Team (
    projectTeamId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projectId NUMBER NOT NULL,
    teamId NUMBER NOT NULL,
    CONSTRAINT fk_pt_project FOREIGN KEY (projectId) REFERENCES APP_USER.Project(projectId),
    CONSTRAINT fk_pt_team FOREIGN KEY (teamId) REFERENCES APP_USER.Team(teamId)
);

CREATE TABLE APP_USER.Task (
    taskId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId NUMBER NOT NULL,
    typeId NUMBER NOT NULL,
    content CLOB NOT NULL,
    isFinished NUMBER(1) DEFAULT 0,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estimatedDuration FLOAT,
    finishDate DATE,
    realDuration FLOAT,
    totalHoursWorked NUMBER(10, 2) DEFAULT 0,
    isActive NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_task_finished CHECK (isFinished IN (0, 1)),
    CONSTRAINT chk_task_active CHECK (isActive IN (0, 1)),
    CONSTRAINT fk_task_user FOREIGN KEY (userId) REFERENCES APP_USER.Users(userId),
    CONSTRAINT fk_task_type FOREIGN KEY (typeId) REFERENCES APP_USER.TaskType(typeId)
);

-- 3. Resolver relación circular de Team -> Manager (User)
ALTER TABLE APP_USER.Team ADD CONSTRAINT fk_team_manager 
FOREIGN KEY (managerId) REFERENCES APP_USER.Users(userId);

-- 4. Agregar las columnas 'everFinished' y 'taskStatus' en Task, y eliminar 'isFinished'
ALTER TABLE APP_USER.Task ADD (
    everFinished NUMBER(1) DEFAULT 0,
    taskStatus VARCHAR2(20) DEFAULT 'Pendiente'
);

ALTER TABLE APP_USER.Task DROP COLUMN isFinished;

ALTER TABLE APP_USER.Task ADD CONSTRAINT chk_task_status CHECK (taskStatus IN ('Pendiente', 'En curso', 'Finalizada'));
