spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
#oracle.jdbc.fanEnabled=false
##this is not used when deployed in kubernetes. Just for local testing
#spring.datasource.url=jdbc:oracle:thin:@adbps_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_ADBPS
#spring.datasource.username=admin
#spring.datasource.password=WELcome12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##Properties of UCP
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

##Logging properties for UCP
logging.level.root=info
logging.file.name=logs.log
logging.level.oracle.ucp=trace
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE

deepseek.api.key=sk-test
deepseek.api.url=https://api.deepseek.com/v1/chat/completions

#spring.security.user.name=psong
#spring.security.user.password=WELcome12345

telegram.bot.token=8599990664:AAEKWJnC8zovPAQu4NNbzib5X-2mKnGGfZQ
telegram.bot.name=a01638979_bot

spring.jpa.properties.hibernate.default_schema=APP_USER
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl